---
- name: motd
  hosts: servers
  gather_facts: True
  vars:
    system_owner: Calvin_Locklear
    email_address: locklear@redhat.com 
  tasks:
    - name: use the template
      template:
        src: templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
