---
- name: Enable web
  hosts: crew
  become: yes
  tasks:
    - name: install latest versions
      yum:
        name: 
          - httpd
          - firewalld
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: enable httpd
      service: 
        name: httpd
        enabled: yes

    - name: firewall for http
      ansible.posix.firewalld:
        permanent: yes
        state: enabled
        immediate: yes
        service: "{{ item }}"
      with_items:
        - http
        - https
        
    - name: restart firewalld
      service:
        name: firewalld
        state: reloaded
        
    - name: test html page
      copy:
        src: index.html
        dest: /var/www/html/index.html
